# Generated by Django 2.1.5 on 2019-02-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_forms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='users',
            new_name='user',
        ),
    ]
